---
title: 异常：invalidArg 函数
description: 了解F# "invalidArg" 函数如何生成自变量异常。
ms.date: 05/16/2016
ms.openlocfilehash: 6b1c5fdb5a541da336977d3a67d471302edb36b6
ms.sourcegitcommit: a2d0e1f66367367065bc8dc0dde488ab536da73f
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/18/2019
ms.locfileid: "71083015"
---
# <a name="exceptions-the-invalidarg-function"></a><span data-ttu-id="ff5f0-103">异常：invalidArg 函数</span><span class="sxs-lookup"><span data-stu-id="ff5f0-103">Exceptions: The invalidArg Function</span></span>

<span data-ttu-id="ff5f0-104">`invalidArg`函数生成参数异常。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-104">The `invalidArg` function generates an argument exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="ff5f0-105">语法</span><span class="sxs-lookup"><span data-stu-id="ff5f0-105">Syntax</span></span>

```fsharp
invalidArg parameter-name error-message-string
```

## <a name="remarks"></a><span data-ttu-id="ff5f0-106">备注</span><span class="sxs-lookup"><span data-stu-id="ff5f0-106">Remarks</span></span>

<span data-ttu-id="ff5f0-107">前面的语法中的参数名称是一个字符串，其参数的名称无效。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-107">The parameter-name in the previous syntax is a string with the name of the parameter whose argument was invalid.</span></span> <span data-ttu-id="ff5f0-108">*错误消息字符串*是文本字符串或类型`string`的值。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-108">The *error-message-string* is a literal string or a value of type `string`.</span></span> <span data-ttu-id="ff5f0-109">它将成为`Message`异常对象的属性。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-109">It becomes the `Message` property of the exception object.</span></span>

<span data-ttu-id="ff5f0-110">生成`invalidArg`的异常是一个`System.ArgumentException`异常。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-110">The exception generated by `invalidArg` is a `System.ArgumentException` exception.</span></span> <span data-ttu-id="ff5f0-111">下面的代码演示`invalidArg`如何使用来引发异常。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-111">The following code illustrates the use of `invalidArg` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6101.fs)]

<span data-ttu-id="ff5f0-112">输出如下所示，后跟堆栈跟踪（未显示）。</span><span class="sxs-lookup"><span data-stu-id="ff5f0-112">The output is the following, followed by a stack trace (not shown).</span></span>

```console
December
January
System.ArgumentException: Month parameter out of range.
```

## <a name="see-also"></a><span data-ttu-id="ff5f0-113">请参阅</span><span class="sxs-lookup"><span data-stu-id="ff5f0-113">See also</span></span>

- [<span data-ttu-id="ff5f0-114">异常处理</span><span class="sxs-lookup"><span data-stu-id="ff5f0-114">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="ff5f0-115">异常类型</span><span class="sxs-lookup"><span data-stu-id="ff5f0-115">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="ff5f0-116">异常：`try...with`表达式</span><span class="sxs-lookup"><span data-stu-id="ff5f0-116">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="ff5f0-117">异常：`try...finally`表达式</span><span class="sxs-lookup"><span data-stu-id="ff5f0-117">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="ff5f0-118">异常：`raise` 函数</span><span class="sxs-lookup"><span data-stu-id="ff5f0-118">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
- [<span data-ttu-id="ff5f0-119">异常：`failwith`函数</span><span class="sxs-lookup"><span data-stu-id="ff5f0-119">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)
