---
title: “Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 6906cb743e6f36acfbf51a5a38d03bd05fde98e2
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 01/23/2019
ms.locfileid: "54598758"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>“Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数
`Throw` 语句外的 `Catch` 语句必须提供异常对象的名称。  
  
 **错误 ID:** BC30666  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1.  指定派生自 `System.Exception`的异常对象的名称。  
  
2.  重构代码，以便 `Throw` 语句位于 `Catch` 块中。  
  
## <a name="see-also"></a>请参阅
- [Throw 语句](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- [在 Visual Basic 中的异常类](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)
- [Visual Basic 中的异常与错误处理](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
