---
title: Catch 块永远不会到达;&lt;异常&gt;已在上面处理同一个 Try 语句
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 37fe7ec852f191c249c59561d2e1f30a6efbb50a
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/22/2018
ms.locfileid: "53775143"
---
# <a name="catch-block-never-reached-ltexceptiongt-handled-above-in-the-same-try-statement"></a>Catch 块永远不会到达;&lt;异常&gt;已在上面处理同一个 Try 语句
无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **错误 ID:** BC42031  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除多余的语句。  
  
## <a name="see-also"></a>请参阅  
 [如何：在 Visual Basic 中捕获异常](https://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)  
 [如何：测试具有的代码...在 Visual Basic 中捕获块](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [如何：在 Visual Basic 中的 Catch 块中的筛选器错误](https://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)  
 [演练：结构化的异常处理 (Visual Basic)](https://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
